const PdfPrinter = require("pdfmake");
const convertImageToBase64 = require("../convertImage");

const formatDate = (dateString) => {
    if (!dateString) return "N/A";
    const date = new Date(dateString);
    return date.toLocaleDateString("en-US", {
        day: "2-digit",
        month: "2-digit",
        year: "numeric",
    });
};

module.exports = (data) => ({
    content: [
        {
            columns: [
                {
                    image: "data:image/png;base64," + convertImageToBase64("./images/logo_officedesign.png"),
                    width: 140,
                },
                {
                    text:
                        "บริษัท ออฟฟิศดีไซน์ จำกัด (สำนักงานใหญ่)\n" +
                        "เลขที่ 304 อาคาร วานิชเพลส อารีย์ ห้องเลขที่ 2208 ชั้นที่ 22\n" +
                        "ถนน พหลโยธิน แขวงสามเสนใน เขตพญาไท กรุงเทพมหานคร 10400\n" +
                        "เลขประจำตัวผู้เสียภาษี 0105547064270\n" +
                        "โทร : 02-623-1515",
                    alignment: "right",
                    fontSize: 10,
                },
            ],
        },

        { text: "เอกสารการติดตั้งระบบและอุปกรณ์", alignment: "center", style: "header" },
        { text: "POS / KIOSK / Printer / Queue / CRM / E - Menu / Warehouse", alignment: "center", style: "normal" },
        {
            table: {
                widths: [420, '*'],
                body: [
                    [
                        { text: "เอกสารเลขที่ : ", alignment: "right" },
                        { text: data.document_delivery_number, alignment: "left", color: "#4285f4", bold: true },
                    ],
                ],
            },
            layout: "noBorders",
        },
        {
            table: {
                widths: [70, 150, 'auto', 130, 'auto', '*'],
                body: [
                    [
                        { text: "บริษัท / ร้าน : ", alignment: "right" },
                        { text: data.company_name, alignment: "left", color: "#4285f4", bold: true },
                        { text: "สาขา : ", alignment: "right" },
                        { text: data.branch_name, alignment: "left", color: "#4285f4", bold: true },
                        { text: "โทร : ", alignment: "right" },
                        { text: " ", alignment: "left", color: "#4285f4", bold: true },
                    ],
                ],
            },
            layout: "noBorders",
        },
        {
            table: {
                widths: [66, 45, 45, 45, 45, 45, 45, 45, 45, 45],
                body: [
                    [
                        { text: "\n", alignment: "right", colSpan: 6 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        { text: "ขั้นตอนการจัดส่งอุปกรณ์ไปยังบริษัท / ร้าน : ", alignment: "right", colSpan: 4 },
                        {},
                        {},
                        {},
                        { image: "data:image/png;base64," + convertImageToBase64(data.firstSection.installChecked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "เจ้าหน้าที่เดินทางไปติดตั้ง", alignment: "left", colSpan: 2 },
                        {},
                        { image: "data:image/png;base64," + convertImageToBase64(data.firstSection.sendChecked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "ส่งเครื่องไป", alignment: "left", colSpan: 2 },
                        {},
                    ],
                    [
                        { text: " ", alignment: "right", colSpan: 4 },
                        {},
                        {},
                        {},
                        { image: "data:image/png;base64," + convertImageToBase64(data.firstSection.onlineChecked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "ติดตั้งระบบ Online", alignment: "left", colSpan: 2 },
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        { text: "\n", alignment: "right", colSpan: 4 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        { image: "data:image/png;base64," + convertImageToBase64(data.secondSection.posChecked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "ชุด POS และ อุปกรณ์", alignment: "left", colSpan: 4 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        { image: "data:image/png;base64," + convertImageToBase64(data.secondSection.monitor1Checked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "VIVIPOS (Monitor 1)", alignment: "left", colSpan: 2 },
                        {},
                        {},
                        { image: "data:image/png;base64," + convertImageToBase64(data.secondSection.monitor2Checked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "VIVIPOS (Monitor 2)", alignment: "left", colSpan: 2 },
                        {},
                        {},
                        {},
                        {},
                    ],
                ],
            },
            layout: "noBorders",
        },
        {
            table: {
                widths: [66, 45, 45, 45, 45, 75, '*', 45, 45, 45],
                body: [
                    [
                        { image: "data:image/png;base64," + convertImageToBase64(data.secondSection.receiptPrinterChecked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "Receipt Printer", alignment: "left", colSpan: 2 },
                        {},
                        {},
                        { image: "data:image/png;base64," + convertImageToBase64(data.secondSection.labelPrinterChecked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "Label Printer", alignment: "left", colSpan: 2 },
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        { image: "data:image/png;base64," + convertImageToBase64(data.secondSection.kitchenPrinterChecked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "Kitchen Printer", alignment: "left", colSpan: 2 },
                        {},
                        {},
                        { image: "data:image/png;base64," + convertImageToBase64(data.secondSection.otherChecked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "อุปกรณ์อื่นๆ โปรดระบุ", alignment: "left" },
                        { text: `${data.secondSection.otherChecked ? `${data.description_second_section}` : "......................................................"}`, alignment: "left", colSpan: 4, color: `${data.secondSection.otherChecked ? "#4285f4" : "#000000"}`, bold: `${data.secondSection.otherChecked}` },
                        {},
                        {},
                        {},
                    ],
                ],
            },
            layout: "noBorders",
        },
        {
            table: {
                widths: [66, 45, 45, 45, 45, 45, 45, 45, 45, 45],
                body: [
                    [
                        { text: "\n", alignment: "right", colSpan: 4 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        { image: "data:image/png;base64," + convertImageToBase64(data.thirdSection.kioskChecked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "KIOSK", alignment: "left", colSpan: 2 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        { image: "data:image/png;base64," + convertImageToBase64(data.thirdSection.queueChecked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "ระบบ Queue", alignment: "left", colSpan: 2 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        { image: "data:image/png;base64," + convertImageToBase64(data.thirdSection.crmChecked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "ระบบ CRM", alignment: "left", colSpan: 2 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        { image: "data:image/png;base64," + convertImageToBase64(data.thirdSection.eMenuChecked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "ระบบ E - Menu", alignment: "left", colSpan: 2 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        { image: "data:image/png;base64," + convertImageToBase64(data.thirdSection.warehouseChecked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "ระบบ Warehouse", alignment: "left", colSpan: 2 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                ],
            },
            layout: "noBorders",
        },
        {
            table: {
                widths: [66, 75, '*'],
                body: [
                    [
                        { image: "data:image/png;base64," + convertImageToBase64(data.thirdSection.otherChecked ? "./images/checkboxTrue.png" : "./images/checkboxFalse.png"), width: 13, alignment: "right", margin: [0, 1] },
                        { text: "อุปกรณ์อื่นๆ โปรดระบุ", alignment: "left" },
                        { text: `${data.thirdSection.otherChecked ? `${data.description_third_section}` : "................................................................"}`, alignment: "left", color: `${data.thirdSection.otherChecked ? "#4285f4" : "#000000"}`, bold: `${data.thirdSection.otherChecked}` },
                    ],
                ],
            },
            layout: "noBorders",
        },
        {
            table: {
                widths: [66, 45, 45, 45, 45, 45, 45, 45, 45, 45],
                body: [
                    [
                        { text: "\n", alignment: "right", colSpan: 6 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        {},
                        { text: "รายละเอียดเพิ่มเติม / หมายเหตุ : ....................................................................................................................................................", alignment: "left", colSpan: 8 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        {},
                        { text: "............................................................................................................................................................................................................", alignment: "left", colSpan: 8 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        {},
                        { text: "............................................................................................................................................................................................................", alignment: "left", colSpan: 8 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                ],
            },
            layout: "noBorders",
        },
        {
            table: {
                widths: [66, 35, 40, 32, 64, 45, 35, 30, 40, 45],
                body: [
                    [
                        { text: "\n", alignment: "right", colSpan: 6 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        { text: "\n", alignment: "right", colSpan: 6 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        { text: "พนักงานผู้ให้บริการ : ", alignment: "right" },
                        { text: "..........................................", colSpan: 2 },
                        {},
                        { text: "ตำแหน่ง : ", alignment: "center" },
                        { text: "................................" },
                        { text: "ผู้รับบริการ : ", alignment: "right" },
                        { text: ".....................................", colSpan: 2 },
                        {},
                        { text: "ตำแหน่ง :", alignment: "center" },
                        { text: "....................." },
                    ],
                    [
                        {},
                        { text: "(กรุณาเขียนตัวบรรจง)", colSpan: 2, alignment: "center" },
                        {},
                        {},
                        {},
                        {},
                        { text: "(กรุณาเขียนตัวบรรจง)", colSpan: 2, alignment: "center" },
                        {},
                        {},
                        {},
                    ],
                    [
                        { text: "วันที่ : ", alignment: "right" },
                        { text: "..........................................", colSpan: 2 },
                        {},
                        {},
                        {},
                        { text: "วันที่ : ", alignment: "right" },
                        { text: ".....................................", colSpan: 2 },
                        {},
                        {},
                        {},
                    ],
                    [
                        { text: "\n", alignment: "right", colSpan: 6 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        { text: "\n", alignment: "right", colSpan: 6 },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        {},
                        { text: "ผู้รับบริการกรุณาตรวจสอบและยืนยันการได้รับบริการแล้ว", colSpan: 5, color: "#666666", alignment: "left" },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                    [
                        { text: "หมายเหตุ :", color: "#666666", alignment: "right" },
                        { text: "หากพนักงานไม่ได้เดินทางไปติดตั้ง พนักงานเซ็นยืนยันจบสิ้นงานหลังจากได้รับการยืนยันจากลูกค้าว่าเครื่อง / ระบบสามารถใช้งานได้แล้ว", colSpan: 9, color: "#666666", alignment: "left" },
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                        {},
                    ],
                ]
            },
            layout: "noBorders",
        }
    ],

    pageSize: "A4",
    pageOrientation: "portrait",
    pageMargins: [30, 30, 30, 30], // เพิ่ม top margin ให้ header ไม่ทับ content
    styles: {
        header: { fontSize: 20, bold: true },
        subheader: { fontSize: 14, bold: true },
        normal: { fontSize: 12 },
    },
});
