version: '3.8'

services:
  directus:
    image: directus/directus:latest
    container_name: directus
    ports:
      - "8055:8055"
    environment:
      DB_CLIENT: pg
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_DATABASE: directus-11
      DB_USER: postgres
      DB_PASSWORD: 1234
      KEY: "5fab99bc-056d-4b87-9c21-f208e7cf8a38"
      SECRET: "00ed0abb-9739-49d3-aca1-9f11eb313a29"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "*"
      CORS_METHODS: "GET,POST,PATCH,DELETE,OPTIONS"
      CORS_HEADERS: "Content-Type,Authorization"
      CORS_ALLOWED_ORIGINS: "http://localhost:8080"
      PUBLIC_URL: "http://localhost:8055/"
      EXTENSIONS_AUTO_RELOAD: "true"
    volumes:
      - ./extensions:/directus/extensions/
      - directus_data:/data

  directus_test:
    image: directus/directus:latest
    container_name: directus_test
    ports:
      - "8056:8055"
    environment:
      DB_CLIENT: pg
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_DATABASE: directus-11-test
      DB_USER: postgres
      DB_PASSWORD: 1234
      KEY: "test-5fab99bc-056d-4b87-9c21-f208e7cf8a38"
      SECRET: "test-00ed0abb-9739-49d3-aca1-9f11eb313a29"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "*"
      CORS_METHODS: "GET,POST,PATCH,DELETE,OPTIONS"
      CORS_HEADERS: "Content-Type,Authorization"
      CORS_ALLOWED_ORIGINS: "http://localhost:8080"
      PUBLIC_URL: "http://localhost:8055/"
      EXTENSIONS_AUTO_RELOAD: "true"
    volumes:
      - ./extensions:/directus/extensions/
      - directus_test_data:/data

volumes:
  directus_data:
    driver: local
  directus_test_data:
    driver: local
